
L = []
L.append('"""Stage 7 API: Industry Sandbox endpoints."""')
L.append('from __future__ import annotations')
L.append('import json')
L.append('from fastapi import Depends, HTTPException')
L.append('from pydantic import BaseModel, field_validator')
L.append('from sqlalchemy import or_, func')
L.append('from sqlalchemy.orm import Session')
L.append('from models import (')
L.append('    SandboxChallenge, SandboxChallengeSkill, SandboxTask, SandboxResource,')
L.append('    SandboxParticipant, SandboxSubmission, SandboxEvaluation, SandboxEvaluationCriterion, Skill,')
L.append(')')
L.append('import stage7_service as s7')
L.append('')
L.append('class SaveDraftIn(BaseModel):')
L.append('    content: str | None = None')
L.append('    github_url: str | None = None')
L.append('    demo_url: str | None = None')
L.append('    draft_data: dict | None = None')
L.append('')
L.append('class SubmitIn(BaseModel):')
L.append('    content: str | None = None')
L.append('    github_url: str | None = None')
L.append('    demo_url: str | None = None')
L.append('')
L.append('class EvaluationIn(BaseModel):')
L.append('    overall_score: float | None = None')
L.append('    feedback: str | None = None')
L.append('    evaluation_type: str | None = "automated"')
L.append('    criteria: list | None = None')
L.append('    @field_validator("overall_score")')
L.append('    @classmethod')
L.append('    def score_range(cls, v):')
L.append('        if v is not None and (v < 0 or v > 100):')
L.append('            raise ValueError("Score must be between 0 and 100")')
L.append('        return v')
L.append('')
L.append('def _filter_options(db: Session) -> dict:')
L.append('    domains = [r[0] for r in db.query(SandboxChallenge.domain).filter(')
L.append('        SandboxChallenge.domain.isnot(None)).distinct().all() if r[0]]')
L.append('    difficulties = [r[0] for r in db.query(SandboxChallenge.difficulty).distinct().all() if r[0]]')
L.append('    statuses = [r[0] for r in db.query(SandboxChallenge.status).distinct().all() if r[0]]')
L.append('    return {"domains": sorted(domains), "difficulties": sorted(difficulties), "statuses": sorted(statuses)}')
L.append('')
L.append('def register_stage7(app, get_db, me_dep):')
L.append('')
L.append('    @app.get("/api/sandbox/challenges")')
L.append('    def list_challenges(search: str = "", domain: str = "", difficulty: str = "",')
L.append('        status: str = "", skill: str = "", limit: int = 50, db: Session = Depends(get_db)):')
L.append('        q = db.query(SandboxChallenge)')
L.append('        if status: q = q.filter(SandboxChallenge.status == status)')
L.append('        if domain: q = q.filter(func.lower(SandboxChallenge.domain) == domain.lower())')
L.append('        if difficulty: q = q.filter(func.lower(SandboxChallenge.difficulty) == difficulty.lower())')
L.append('        if search and search.strip():')
L.append('            term = f"%{search.strip()}%"')
L.append('            q = q.filter(or_(SandboxChallenge.title.ilike(term),')
L.append('                SandboxChallenge.description.ilike(term), SandboxChallenge.industry.ilike(term)))')
L.append('        if skill and skill.strip():')
L.append('            sr = db.query(Skill).filter(func.lower(Skill.name) == skill.strip().lower()).first()')
L.append('            if sr:')
L.append('                ids = [r[0] for r in db.query(SandboxChallengeSkill.challenge_id)')
L.append('                    .filter(SandboxChallengeSkill.skill_id == sr.id).all()]')
L.append('                q = q.filter(SandboxChallenge.id.in_(ids)) if ids else q.filter(False)')
L.append('            else: return {"challenges": [], "filters": _filter_options(db)}')
L.append('        rows = q.order_by(SandboxChallenge.created_at.desc()).limit(min(max(limit, 1), 100)).all()')
L.append('        return {"challenges": [s7.serialize_challenge(r) for r in rows], "filters": _filter_options(db)}')

L.append('    @app.get("/api/sandbox/my-challenges")')
L.append('    def my_challenges(cu=Depends(me_dep), db: Session = Depends(get_db)):')
L.append('        parts = db.query(SandboxParticipant).filter(')
L.append('            SandboxParticipant.user_id == cu.id).order_by(SandboxParticipant.started_at.desc()).all()')
L.append('        out = []')
L.append('        for p in parts:')
L.append('            ch = db.get(SandboxChallenge, p.challenge_id)')
L.append('            if not ch: continue')
L.append('            sub = db.query(SandboxSubmission).filter(')
L.append('                SandboxSubmission.challenge_id == p.challenge_id,')
L.append('                SandboxSubmission.user_id == cu.id).order_by(SandboxSubmission.id.desc()).first()')
L.append('            out.append({"participant": {"id": p.id, "status": p.status},')
L.append('                "challenge": s7.serialize_challenge(ch),')
L.append('                "submission": s7.serialize_submission(sub) if sub else None})')
L.append('        return {"challenges": out}')
L.append('')
L.append('    @app.get("/api/sandbox/my-challenges/{challenge_id}")')
L.append('    def my_challenge_detail(challenge_id: int, cu=Depends(me_dep), db: Session = Depends(get_db)):')
L.append('        ch = db.get(SandboxChallenge, challenge_id)')
L.append('        if not ch: raise HTTPException(status_code=404, detail="Not found")')
L.append('        participant = db.query(SandboxParticipant).filter(')
L.append('            SandboxParticipant.challenge_id == challenge_id,')
L.append('            SandboxParticipant.user_id == cu.id).first()')
L.append('        if not participant: raise HTTPException(status_code=404, detail="Not joined")')
L.append('        sub = db.query(SandboxSubmission).filter(')
L.append('            SandboxSubmission.challenge_id == challenge_id,')
L.append('            SandboxSubmission.user_id == cu.id).order_by(SandboxSubmission.id.desc()).first()')
L.append('        evaluation = None')
L.append('        if sub and sub.status == "submitted":')
L.append('            ev = db.query(SandboxEvaluation).filter(')
L.append('                SandboxEvaluation.submission_id == sub.id).first()')
L.append('            if ev: evaluation = s7.serialize_evaluation(ev)')
L.append('        data = s7.serialize_challenge(ch)')
L.append('        data["tasks"] = [s7.serialize_task(t) for t in ch.tasks]')
L.append('        data["resources"] = [s7.serialize_resource(r) for r in ch.resources]')
L.append('        data["participant"] = {"id": participant.id, "status": participant.status}')
L.append('        data["submission"] = s7.serialize_submission(sub) if sub else None')
L.append('        data["evaluation"] = evaluation')
L.append('        return data')
L.append('')
L.append('    @app.get("/api/sandbox/workspace/{challenge_id}")')

L.append('    @app.put("/api/sandbox/workspace/{challenge_id}/draft")')
L.append('    def save_draft(challenge_id: int, data: SaveDraftIn, cu=Depends(me_dep), db: Session = Depends(get_db)):')
L.append('        ch = db.get(SandboxChallenge, challenge_id)')
L.append('        if not ch: raise HTTPException(status_code=404, detail="Not found")')
L.append('        sub = s7.get_or_create_submission(db, challenge_id, cu.id)')
L.append('        if sub.status != "draft": raise HTTPException(status_code=400, detail="Already sent")')
L.append('        if data.content is not None: sub.content = data.content')
L.append('        if data.github_url is not None: sub.github_url = data.github_url.strip() if data.github_url else None')
L.append('        if data.demo_url is not None: sub.demo_url = data.demo_url.strip() if data.demo_url else None')
L.append('        if data.draft_data is not None:')
L.append('            try: sub.draft_data = json.dumps(data.draft_data)[:5000]')
L.append('            except Exception: pass')
L.append('        sub.updated_at = func.now()')
L.append('        db.commit()')
L.append('        return {"submission": s7.serialize_submission(sub), "message": "Draft saved"}')
L.append('')
L.append('    @app.post("/api/sandbox/workspace/{challenge_id}/submit")')
L.append('    def submit_solution(challenge_id: int, data: SubmitIn, cu=Depends(me_dep), db: Session = Depends(get_db)):')
L.append('        ch = db.get(SandboxChallenge, challenge_id)')
L.append('        if not ch: raise HTTPException(status_code=404, detail="Not found")')
L.append('        participant = db.query(SandboxParticipant).filter(')
L.append('            SandboxParticipant.challenge_id == challenge_id,')
L.append('            SandboxParticipant.user_id == cu.id).first()')
L.append('        if not participant: raise HTTPException(status_code=400, detail="Join first")')
L.append('        sub = db.query(SandboxSubmission).filter(')
L.append('            SandboxSubmission.challenge_id == challenge_id,')
L.append('            SandboxSubmission.user_id == cu.id,')
L.append('            SandboxSubmission.status == "draft").order_by(SandboxSubmission.attempt.desc()).first()')
L.append('        if not sub: raise HTTPException(status_code=400, detail="No draft")')

L.append('    @app.post("/api/sandbox/submissions/{submission_id}/evaluate")')
L.append('    def evaluate_submission(submission_id: int, data: EvaluationIn, cu=Depends(me_dep), db: Session = Depends(get_db)):')
L.append('        sub = db.get(SandboxSubmission, submission_id)')
L.append('        if not sub: raise HTTPException(status_code=404, detail="Not found")')
L.append('        if cu.role not in ("admin", "mentor", "faculty"):')
L.append('            raise HTTPException(status_code=403, detail="Not authorized")')
L.append('        ev = db.query(SandboxEvaluation).filter(')
L.append('            SandboxEvaluation.submission_id == submission_id).first()')
L.append('        if not ev: ev = SandboxEvaluation(submission_id=submission_id); db.add(ev)')
L.append('        ev.overall_score = data.overall_score; ev.feedback = data.feedback')
L.append('        ev.evaluated_by = cu.id; ev.evaluation_type = data.evaluation_type or "automated"')
L.append('        if data.criteria:')
L.append('            for c in ev.criteria: db.delete(c)')
L.append('            db.flush()')
L.append('            for c in data.criteria:')
L.append('                db.add(SandboxEvaluationCriterion(evaluation_id=ev.id,')
L.append('                    name=c.get("name", "Criterion"), score=float(c.get("score", 0)),')
L.append('                    max_score=float(c.get("max_score", 100)), comment=c.get("comment")))')
L.append('        participant = db.query(SandboxParticipant).filter(')
L.append('            SandboxParticipant.challenge_id == sub.challenge_id,')
L.append('            SandboxParticipant.user_id == sub.user_id).first()')
L.append('        if participant:')
L.append('            participant.status = "completed" if (data.overall_score is not None and data.overall_score >= 50) else "evaluated"')
L.append('            participant.completed_at = func.now() if participant.status == "completed" else None')
L.append('        db.commit(); db.refresh(ev)')
L.append('        evidence = s7.create_sandbox_evidence(db, ev); db.commit()')
L.append('        return {"evaluation": s7.serialize_evaluation(ev), "evidence_created": len(evidence)}')
L.append('')
L.append('    @app.get("/api/sandbox/submissions/{submission_id}")')
L.append('    def get_submission(submission_id: int, cu=Depends(me_dep), db: Session = Depends(get_db)):')
L.append('        sub = db.get(SandboxSubmission, submission_id)')
L.append('        if not sub: raise HTTPException(status_code=404, detail="Not found")')
L.append('        if sub.user_id != cu.id and cu.role not in ("admin", "mentor", "faculty"):')
L.append('            raise HTTPException(status_code=403, detail="Not authorized")')
L.append('        ev = db.query(SandboxEvaluation).filter(SandboxEvaluation.submission_id == sub.id).first()')
L.append('        data = s7.serialize_submission(sub)')
L.append('        data["evaluation"] = s7.serialize_evaluation(ev) if ev else None')
L.append('        return data')
L.append('')
L.append('    @app.get("/api/sandbox/dashboard")')
L.append('    def sandbox_dashboard(cu=Depends(me_dep), db: Session = Depends(get_db)):')
L.append('        return {"stats": s7.student_dashboard_stats(db, cu.id)}')
L.append('')
L.append('    @app.get("/api/sandbox/recommendations")')
L.append('    def sandbox_recommendations(cu=Depends(me_dep), db: Session = Depends(get_db)):')
L.append('        return {"recommendations": s7.recommend_challenges(db, cu.id)}')
L.append('')
L.append('    @app.post("/api/sandbox/admin/challenges")')
L.append('    def create_challenge(data: dict, cu=Depends(me_dep), db: Session = Depends(get_db)):')
L.append('        if cu.role != "admin": raise HTTPException(status_code=403, detail="Admin only")')
L.append('        title = (data.get("title") or "").strip()')
L.append('        if not title: raise HTTPException(status_code=400, detail="Title required")')
L.append('        slug = (data.get("slug") or title.lower().replace(" ", "-")[:60]).strip()')
L.append('        base = slug; c = 1')
L.append('        while db.query(SandboxChallenge).filter(SandboxChallenge.slug == slug).first():')
L.append('            slug = f"{base}-{c}"; c += 1')
L.append('        ch = SandboxChallenge(title=title, slug=slug, description=data.get("description", ""),')
L.append('            industry=data.get("industry"), domain=data.get("domain"),')
L.append('            difficulty=data.get("difficulty", "intermediate"), company_name=data.get("company_name"),')
L.append('            is_demo=data.get("is_demo", False), created_by=cu.id)')
L.append('        if data.get("evaluation_criteria"): ch.evaluation_criteria = json.dumps(data["evaluation_criteria"])')
L.append('        db.add(ch); db.flush()')
L.append('        for sk in (data.get("skills") or []):')
L.append('            sn = (sk.get("name") or sk if isinstance(sk, str) else "").strip()')
L.append('            if not sn: continue')
L.append('            so = db.query(Skill).filter(func.lower(Skill.name) == sn.lower()).first()')
L.append('            if not so: so = Skill(name=sn); db.add(so); db.flush()')
L.append('            db.add(SandboxChallengeSkill(challenge_id=ch.id, skill_id=so.id))')
L.append('        for i, t in enumerate(data.get("tasks") or []):')
L.append('            db.add(SandboxTask(challenge_id=ch.id, title=(t.get("title") or f"Task {i+1}").strip(),')
L.append('                task_type=t.get("task_type", "text_response"), order_index=i))')
L.append('        db.commit()')
L.append('        return {"challenge": s7.serialize_challenge(ch), "message": "Created"}')

with open("stage7_api.py", "w", encoding="utf-8") as f:
    f.write("\\n".join(L) + "\\n")
print("stage7_api.py written OK")

L.append('        if data.content is not None: sub.content = data.content')
L.append('        if data.github_url is not None: sub.github_url = data.github_url.strip() if data.github_url else None')
L.append('        if data.demo_url is not None: sub.demo_url = data.demo_url.strip() if data.demo_url else None')
L.append('        sub.status = "submitted"; sub.submitted_at = func.now(); sub.updated_at = func.now()')
L.append('        participant.status = "submitted"; db.commit()')
L.append('        return {"submission": s7.serialize_submission(sub), "message": "Submitted"}')

L.append('    def get_workspace(challenge_id: int, cu=Depends(me_dep), db: Session = Depends(get_db)):')
L.append('        ch = db.get(SandboxChallenge, challenge_id)')
L.append('        if not ch: raise HTTPException(status_code=404, detail="Not found")')
L.append('        participant = db.query(SandboxParticipant).filter(')
L.append('            SandboxParticipant.challenge_id == challenge_id,')
L.append('            SandboxParticipant.user_id == cu.id).first()')
L.append('        if not participant: raise HTTPException(status_code=400, detail="Join first")')
L.append('        sub = s7.get_or_create_submission(db, challenge_id, cu.id)')
L.append('        db.commit()')
L.append('        data = s7.serialize_challenge(ch)')
L.append('        data["tasks"] = [s7.serialize_task(t) for t in ch.tasks]')
L.append('        data["resources"] = [s7.serialize_resource(r) for r in ch.resources]')
L.append('        data["submission"] = s7.serialize_submission(sub)')
L.append('        return data')
L.append('')

L.append('')
L.append('    @app.get("/api/sandbox/challenges/{challenge_id}")')
L.append('    def get_challenge(challenge_id: int, db: Session = Depends(get_db)):')
L.append('        row = db.get(SandboxChallenge, challenge_id)')
L.append('        if not row: raise HTTPException(status_code=404, detail="Challenge not found")')
L.append('        data = s7.serialize_challenge(row)')
L.append('        data["tasks"] = [s7.serialize_task(t) for t in row.tasks]')
L.append('        data["resources"] = [s7.serialize_resource(r) for r in row.resources]')
L.append('        return data')
L.append('')
L.append('    @app.post("/api/sandbox/challenges/{challenge_id}/start")')
L.append('    def start_challenge(challenge_id: int, cu=Depends(me_dep), db: Session = Depends(get_db)):')
L.append('        ch = db.get(SandboxChallenge, challenge_id)')
L.append('        if not ch: raise HTTPException(status_code=404, detail="Not found")')
L.append('        if ch.status != "open": raise HTTPException(status_code=400, detail="Not open")')
L.append('        p = s7.get_or_create_participant(db, challenge_id, cu.id)')
L.append('        db.commit()')
L.append('        return {"participant": {"id": p.id, "status": p.status,')
L.append('            "started_at": p.started_at.isoformat() if p.started_at else None},')
L.append('            "message": "Challenge started" if p.status == "in_progress" else "Already joined"}')
L.append('')
