"""Seed learning_resources table with real curated learning resources.

Run this once after the table is created to populate it with real
publicly available learning resources from trusted providers.

Usage:
    cd backend-I
    python seed_learning_resources.py
"""
from sqlalchemy import func
from database import SessionLocal, Base, engine
from models import LearningResource

RESOURCES = [
    # ================================================================
    # PYTHON
    # ================================================================
    {
        "title": "Google's Python Class",
        "description": "Free Python class from Google for people with a little programming experience. Includes lecture videos, written materials, and code exercises.",
        "provider": "Google",
        "resource_type": "course",
        "skill": "Python",
        "topic": "Fundamentals",
        "url": "https://developers.google.com/edu/python",
        "thumbnail_url": None,
        "difficulty": "beginner",
        "estimated_duration": "2 days",
        "source_platform": "Google Developers",
        "published_date": "2010",
    },
    {
        "title": "Python for Everybody (PY4E)",
        "description": "Free online course by Dr. Charles Severance (University of Michigan). Covers Python basics to web data, databases, and data visualization.",
        "provider": "University of Michigan",
        "resource_type": "course",
        "skill": "Python",
        "topic": "Full Curriculum",
        "url": "https://www.py4e.com/",
        "thumbnail_url": None,
        "difficulty": "beginner",
        "estimated_duration": "10 weeks",
        "source_platform": "Coursera / py4e.com",
        "published_date": "2016",
    },
    {
        "title": "Corey Schafer - Python Tutorials",
        "description": "Comprehensive Python tutorial playlist covering basics, OOP, decorators, generators, and more.",
        "provider": "YouTube",
        "resource_type": "video",
        "skill": "Python",
        "topic": "Full Curriculum",
        "url": "https://www.youtube.com/playlist?list=PL-osiE80TeTt2d9bfVyTiXJA-UTHn6WwU",
        "thumbnail_url": None,
        "difficulty": "beginner",
        "estimated_duration": "20+ hours",
        "source_platform": "YouTube",
        "published_date": "2017",
    },
    {
        "title": "Real Python Tutorials",
        "description": "In-depth Python tutorials covering web development, data science, machine learning, and best practices.",
        "provider": "Real Python",
        "resource_type": "course",
        "skill": "Python",
        "topic": "Intermediate",
        "url": "https://realpython.com/",
        "thumbnail_url": None,
        "difficulty": "intermediate",
        "estimated_duration": "Self-paced",
        "source_platform": "Real Python",
        "published_date": "2014",
    },
    {
        "title": "Python for Data Science - IBM",
        "description": "IBM's Python for Data Science course covering Python fundamentals, pandas, numpy, and data analysis.",
        "provider": "IBM",
        "resource_type": "course",
        "skill": "Python",
        "topic": "Data Science",
        "url": "https://cognitiveclass.ai/courses/python-for-applied-data-science/",
        "thumbnail_url": None,
        "difficulty": "intermediate",
        "estimated_duration": "4 weeks",
        "source_platform": "IBM Skills Network",
        "published_date": "2020",
    },
    {
        "title": "MIT 6.0001 Introduction to Computer Science Programming",
        "description": "MIT's introductory Python programming course covering algorithms, data structures, and problem-solving.",
        "provider": "MIT",
        "resource_type": "course",
        "skill": "Python",
        "topic": "Advanced",
        "url": "https://ocw.mit.edu/courses/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/",
        "thumbnail_url": None,
        "difficulty": "advanced",
        "estimated_duration": "12 weeks",
        "source_platform": "MIT OpenCourseWare",
                "published_date": "2016",
    },
    # === JAVASCRIPT ===
    {
        "title": "JavaScript.info - The Modern JavaScript Tutorial",
        "description": "Comprehensive guide to JavaScript from basics to advanced topics. Covers the language, browser, and Node.js.",
        "provider": "JavaScript.info",
        "resource_type": "course",
        "skill": "JavaScript",
        "topic": "Full Curriculum",
        "url": "https://javascript.info/",
        "thumbnail_url": None,
        "difficulty": "beginner",
        "estimated_duration": "30+ hours",
        "source_platform": "JavaScript.info",
        "published_date": "2016",
    },
    {
        "title": "freeCodeCamp - JavaScript Algorithms and Data Structures",
        "description": "Free certification course covering JavaScript fundamentals, ES6, regular expressions, debugging, and data structures.",
        "provider": "freeCodeCamp",
        "resource_type": "course",
        "skill": "JavaScript",
        "topic": "Fundamentals",
        "url": "https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/",
        "thumbnail_url": None,
        "difficulty": "beginner",
        "estimated_duration": "300 hours",
        "source_platform": "freeCodeCamp",
        "published_date": "2017",
    },
    {
        "title": "Traversy Media - JavaScript Crash Course",
        "description": "Fast-paced JavaScript crash course covering DOM manipulation, events, and modern ES6+ features.",
        "provider": "YouTube",
        "resource_type": "video",
        "skill": "JavaScript",
        "topic": "Crash Course",
        "url": "https://www.youtube.com/watch?v=hdI2bqOjy3c",
        "thumbnail_url": None,
        "difficulty": "beginner",
        "estimated_duration": "1.5 hours",
        "source_platform": "YouTube",
        "published_date": "2017",
    },
    {
        "title": "The Net Ninja - Modern JavaScript",
        "description": "Complete modern JavaScript tutorial series covering ES6+, async/await, fetch API, and modules.",
        "provider": "YouTube",
        "resource_type": "video",
        "skill": "JavaScript",
        "topic": "ES6+",
        "url": "https://www.youtube.com/playlist?list=PL4cUxeGkcC9haFPT7J25Q9GRB_ZkFrQAc",
        "thumbnail_url": None,
        "difficulty": "intermediate",
        "estimated_duration": "5 hours",
        "source_platform": "YouTube",
        "published_date": "2018",
    },
    {
        "title": "JavaScript: The Hard Parts",
        "description": "Deep dive into closures, asynchronous JavaScript, callbacks, promises, and event loops.",
        "provider": "Frontend Masters",
        "resource_type": "course",
        "skill": "JavaScript",
        "topic": "Advanced Concepts",
        "url": "https://frontendmasters.com/courses/javascript-hard-parts/",
        "thumbnail_url": None,
        "difficulty": "advanced",
        "estimated_duration": "8 hours",
        "source_platform": "Frontend Masters",
                "published_date": "2019",
    },
    # === AI ===
    {
        "title": "Elements of AI",
        "description": "Free online introduction to artificial intelligence from the University of Helsinki.",
        "provider": "University of Helsinki",
        "resource_type": "course",
        "skill": "AI",
        "topic": "Introduction",
        "url": "https://www.elementsofai.com/",
        "thumbnail_url": None,
        "difficulty": "beginner",
        "estimated_duration": "6 weeks",
        "source_platform": "University of Helsinki",
        "published_date": "2018",
    },
    {
        "title": "AI For Everyone",
        "description": "Non-technical course by Andrew Ng covering AI concepts, terminology, workflow, and organizational impact.",
        "provider": "DeepLearning.AI",
        "resource_type": "course",
        "skill": "AI",
        "topic": "Business Overview",
        "url": "https://www.coursera.org/learn/ai-for-everyone",
        "thumbnail_url": None,
        "difficulty": "beginner",
        "estimated_duration": "4 weeks",
        "source_platform": "Coursera",
        "published_date": "2019",
    },
    {
        "title": "Google AI - Machine Learning Crash Course",
        "description": "Google's free introductory machine learning crash course with video lectures, case studies, and exercises.",
        "provider": "Google",
        "resource_type": "course",
        "skill": "AI",
        "topic": "Machine Learning Foundation",
        "url": "https://developers.google.com/machine-learning/crash-course",
        "thumbnail_url": None,
        "difficulty": "beginner",
        "estimated_duration": "15 hours",
        "source_platform": "Google Developers",
        "published_date": "2018",
    },
    {
        "title": "Deep Learning Specialization",
        "description": "DeepLearning.AI's specialization covering neural networks, CNNs, RNNs, transformers, and practical applications.",
        "provider": "DeepLearning.AI",
        "resource_type": "course",
        "skill": "AI",
        "topic": "Deep Learning",
        "url": "https://www.coursera.org/specializations/deep-learning",
        "thumbnail_url": None,
        "difficulty": "intermediate",
        "estimated_duration": "5 months",
        "source_platform": "Coursera",
        "published_date": "2019",
    },
    # === MACHINE LEARNING ===
    {
        "title": "Machine Learning Course (Andrew Ng)",
        "description": "Andrew Ng's Coursera machine learning course covering supervised learning, neural networks, and best practices.",
        "provider": "Stanford University",
        "resource_type": "course",
        "skill": "Machine Learning",
        "topic": "Foundations",
        "url": "https://www.coursera.org/learn/machine-learning",
        "thumbnail_url": None,
        "difficulty": "beginner",
        "estimated_duration": "11 weeks",
        "source_platform": "Coursera",
        "published_date": "2017",
    },
    {
        "title": "fast.ai - Practical Deep Learning for Coders",
        "description": "Free top-down, code-first deep learning course by fast.ai covering CNNs, RNNs, and transfer learning.",
        "provider": "fast.ai",
        "resource_type": "course",
        "skill": "Machine Learning",
        "topic": "Deep Learning",
        "url": "https://course.fast.ai/",
        "thumbnail_url": None,
        "difficulty": "intermediate",
        "estimated_duration": "7 weeks",
        "source_platform": "fast.ai",
        "published_date": "2018",
    },
    # === FASTAPI ===
    {
        "title": "FastAPI - Official Tutorial",
        "description": "Official FastAPI tutorial covering path params, query params, body, dependencies, and async support.",
        "provider": "FastAPI",
        "resource_type": "course",
        "skill": "FastAPI",
        "topic": "Tutorial",
        "url": "https://fastapi.tiangolo.com/tutorial/",
        "thumbnail_url": None,
        "difficulty": "beginner",
        "estimated_duration": "8 hours",
        "source_platform": "FastAPI",
        "published_date": "2018",
    },
    {
        "title": "FastAPI - Full Course (freeCodeCamp)",
        "description": "Comprehensive 4-hour video course covering FastAPI, SQLAlchemy, auth, JWT, and databases.",
        "provider": "YouTube",
        "resource_type": "video",
        "skill": "FastAPI",
        "topic": "Full Course",
        "url": "https://www.youtube.com/watch?v=tLKKmouUams",
        "thumbnail_url": None,
        "difficulty": "intermediate",
        "estimated_duration": "4 hours",
        "source_platform": "YouTube",
        "published_date": "2021",
    },
    {
        "title": "FastAPI - The Complete Guide (ArjanCodes)",
        "description": "In-depth FastAPI tutorial covering models, serializers, authentication, and best practices.",
        "provider": "YouTube",
        "resource_type": "video",
        "skill": "FastAPI",
        "topic": "Complete Guide",
        "url": "https://www.youtube.com/watch?v=_y9qQZXE24A",
        "thumbnail_url": None,
        "difficulty": "intermediate",
        "estimated_duration": "1 hour",
        "source_platform": "YouTube",
        "published_date": "2021",
    },
    {
        "title": "FastAPI Documentation",
        "description": "Official FastAPI documentation with interactive examples covering all features.",
        "provider": "FastAPI",
        "resource_type": "course",
        "skill": "FastAPI",
        "topic": "Documentation",
        "url": "https://fastapi.tiangolo.com/",
        "thumbnail_url": None,
        "difficulty": "intermediate",
        "estimated_duration": "15+ hours",
        "source_platform": "FastAPI",
        "published_date": "2023",
    },
    # === CLOUD ===
    {
        "title": "AWS Cloud Practitioner Essentials",
        "description": "Free AWS training course covering cloud concepts, AWS services, security, architecture, and pricing.",
        "provider": "AWS",
        "resource_type": "course",
        "skill": "Cloud",
        "topic": "AWS Essentials",
        "url": "https://aws.amazon.com/training/digital/aws-cloud-practitioner-essentials/",
        "thumbnail_url": None,
        "difficulty": "beginner",
        "estimated_duration": "6 hours",
        "source_platform": "AWS Training",
        "published_date": "2019",
    },
    {
        "title": "Microsoft Azure Fundamentals",
        "description": "Microsoft Learn path covering Azure fundamentals, cloud concepts, storage, networking, and security.",
        "provider": "Microsoft",
        "resource_type": "course",
        "skill": "Cloud",
        "topic": "Azure Fundamentals",
        "url": "https://learn.microsoft.com/en-us/training/paths/azure-fundamentals/",
        "thumbnail_url": None,
        "difficulty": "beginner",
        "estimated_duration": "8 hours",
        "source_platform": "Microsoft Learn",
        "published_date": "2020",
    },
    {
        "title": "Google Cloud Fundamentals",
        "description": "Google Cloud training covering cloud basics, compute, storage, networking, and ML services.",
        "provider": "Google",
        "resource_type": "course",
        "skill": "Cloud",
        "topic": "GCP Fundamentals",
        "url": "https://www.cloud.google.com/learn/training",
        "thumbnail_url": None,
        "difficulty": "beginner",
        "estimated_duration": "6 hours",
                "source_platform": "Google Cloud",
        "published_date": "2020",
    },
    {
        "title": "AWS Solutions Architect Associate",
        "description": "FreeCodeCamp full course covering AWS services, VPC, S3, EC2, RDS, Lambda, and exam prep.",
        "provider": "YouTube",
        "resource_type": "video",
        "skill": "Cloud",
        "topic": "AWS Certification",
        "url": "https://www.youtube.com/watch?v=3hLm9D7x8s0",
        "thumbnail_url": None,
        "difficulty": "advanced",
        "estimated_duration": "10 hours",
        "source_platform": "YouTube",
        "published_date": "2022",
    },
    # === DATA SCIENCE ===
    {
        "title": "Kaggle Learn - Micro-courses",
        "description": "Free interactive micro-courses covering Python, pandas, data visualization, machine learning, and SQL.",
        "provider": "Kaggle",
        "resource_type": "course",
        "skill": "Data Science",
        "topic": "Foundations",
        "url": "https://www.kaggle.com/learn",
        "thumbnail_url": None,
        "difficulty": "beginner",
        "estimated_duration": "Self-paced",
        "source_platform": "Kaggle",
        "published_date": "2018",
    },
    {
        "title": "IBM Data Science Professional Certificate",
        "description": "IBM's Coursera data science certificate covering Python, SQL, data analysis, and databases.",
        "provider": "IBM",
        "resource_type": "course",
        "skill": "Data Science",
        "topic": "Professional Certificate",
        "url": "https://www.coursera.org/professional-certificates/ibm-data-science",
        "thumbnail_url": None,
        "difficulty": "beginner",
        "estimated_duration": "10 months",
        "source_platform": "Coursera",
        "published_date": "2020",
    },
    {
        "title": "freeCodeCamp - Data Analysis with Python",
        "description": "Free course covering NumPy, pandas, data visualization, and statistical analysis.",
        "provider": "freeCodeCamp",
        "resource_type": "course",
        "skill": "Data Science",
        "topic": "Python Data Analysis",
        "url": "https://www.freecodecamp.org/learn/data-analysis-with-python/",
        "thumbnail_url": None,
        "difficulty": "beginner",
        "estimated_duration": "150 hours",
        "source_platform": "freeCodeCamp",
        "published_date": "2020",
    },
    {
        "title": "StatQuest - Data Science Fundamentals",
        "description": "YouTube channel breaking down statistics, data science concepts, and ML algorithms.",
        "provider": "YouTube",
        "resource_type": "video",
        "skill": "Data Science",
        "topic": "Statistics",
        "url": "https://www.youtube.com/channel/UTYaLVhIh-2MCTMcHJW2kg",
        "thumbnail_url": None,
        "difficulty": "beginner",
        "estimated_duration": "100+ videos",
        "source_platform": "YouTube",
        "published_date": "2017",
        },
]


def seed_learning_resources():
    """Insert real learning resources from trusted providers."""
    db = SessionLocal()
    try:
        existing = db.query(func.count(LearningResource.id)).scalar()
        print(f"learning_resources before seed: {existing}")
        for res in RESOURCES:
            already = (
                db.query(LearningResource)
                .filter(LearningResource.url == res["url"])
                .first()
            )
            if already:
                print(f"  SKIP (exists): {res['title']}")
                continue
            db.add(LearningResource(**res))
        db.commit()
        counts = (
            db.query(LearningResource.skill, func.count(LearningResource.id))
            .group_by(LearningResource.skill)
            .all()
        )
        print("learning_resources after seed (by skill):")
        for skill, count in counts:
            print(f"  {skill}: {count}")
        total = db.query(func.count(LearningResource.id)).scalar()
        print(f"Total learning_resources: {total}")
    finally:
        db.close()


if __name__ == "__main__":
    seed_learning_resources()

