"""Seed learning_resources table with real curated learning resources.

Every row below was verified against its live public page before being
added: the provider really publishes that title at that URL, and
estimated_duration is only filled when the provider page itself states
it (otherwise None - never invented). Published dates are omitted
because provider pages do not reliably expose them.

Verified counts per skill: Python 10, JavaScript 6, AI 5,
Machine Learning 5, FastAPI 4, Cloud 7, Data Science 5 (42 total).
"""

from sqlalchemy import func
from database import SessionLocal, Base, engine
from models import LearningResource

RESOURCES = [
    {
        "title": "Google's Python Class",
        "description": "Free Python class for people with a little programming experience. Includes lecture videos, written materials, and code exercises.",
        "provider": "Google",
        "resource_type": "course",
        "skill": "Python",
        "topic": "Fundamentals",
        "url": "https://developers.google.com/edu/python",
        "thumbnail_url": None,
        "difficulty": "beginner",
        "estimated_duration": None,
        "source_platform": "Google Developers",
        "published_date": None,
    },
    {
        "title": "Python for Everybody (PY4E)",
        "description": "Free course site by Dr. Charles Severance (University of Michigan) covering Python basics through web data, databases, and visualisation.",
        "provider": "University of Michigan",
        "resource_type": "course",
        "skill": "Python",
        "topic": "Full Curriculum",
        "url": "https://www.py4e.com/",
        "thumbnail_url": None,
        "difficulty": "beginner",
        "estimated_duration": None,
        "source_platform": "py4e.com",
        "published_date": None,
    },
    {
        "title": "Python Tutorials",
        "description": "YouTube playlist by Corey Schafer covering Python basics, OOP, decorators, generators, and more.",
        "provider": "Corey Schafer",
        "resource_type": "video",
        "skill": "Python",
        "topic": "Full Curriculum",
        "url": "https://www.youtube.com/playlist?list=PL-osiE80TeTt2d9bfVyTiXJA-UTHn6WwU",
        "thumbnail_url": "https://i.ytimg.com/vi/CqvZ3vGoGs0/hqdefault.jpg",
        "difficulty": "beginner",
        "estimated_duration": None,
        "source_platform": "YouTube",
        "published_date": None,
    },
    {
        "title": "Real Python Tutorials",
        "description": "In-depth Python tutorials covering web development, data science, and best practices.",
        "provider": "Real Python",
        "resource_type": "course",
        "skill": "Python",
        "topic": "Intermediate",
        "url": "https://realpython.com/",
        "thumbnail_url": None,
        "difficulty": "intermediate",
        "estimated_duration": None,
        "source_platform": "Real Python",
        "published_date": None,
    },
    {
        "title": "Python for Data Science",
        "description": "Beginner-friendly IBM Skills Network course (PY0101EN): Python basics, data structures, files, pandas, and NumPy with hands-on labs.",
        "provider": "IBM",
        "resource_type": "course",
        "skill": "Python",
        "topic": "Data Science",
        "url": "https://cognitiveclass.ai/courses/python-for-data-science",
        "thumbnail_url": None,
        "difficulty": "beginner",
        "estimated_duration": "18 Hours",
        "source_platform": "Cognitive Class (IBM Skills Network)",
        "published_date": None,
    },
    {
        "title": "CS50's Introduction to Programming with Python",
        "description": "Harvard CS50P open courseware: functions, variables, conditionals, loops, exceptions, libraries, testing, regex, OOP, and file I/O.",
        "provider": "Harvard University",
        "resource_type": "course",
        "skill": "Python",
        "topic": "Full Curriculum",
        "url": "https://cs50.harvard.edu/python/2022/",
        "thumbnail_url": None,
        "difficulty": "beginner",
        "estimated_duration": None,
        "source_platform": "CS50 OpenCourseWare",
        "published_date": None,
    },
    {
        "title": "Learn Python - Full Course for Beginners [Tutorial]",
        "description": "Full beginner Python tutorial video on the freeCodeCamp.org YouTube channel.",
        "provider": "freeCodeCamp",
        "resource_type": "video",
        "skill": "Python",
        "topic": "Beginner Full Course",
        "url": "https://www.youtube.com/watch?v=rfscVS0vtbw",
        "thumbnail_url": "https://i.ytimg.com/vi/rfscVS0vtbw/hqdefault.jpg",
        "difficulty": "beginner",
        "estimated_duration": None,
        "source_platform": "YouTube",
        "published_date": None,
    },
    {
        "title": "Python for Beginners - Full Course [Programming Tutorial]",
        "description": "Full beginner Python course video on the freeCodeCamp.org YouTube channel.",
        "provider": "freeCodeCamp",
        "resource_type": "video",
        "skill": "Python",
        "topic": "Beginner Full Course",
        "url": "https://www.youtube.com/watch?v=eWRfhZUzrAc",
        "thumbnail_url": "https://i.ytimg.com/vi/eWRfhZUzrAc/hqdefault.jpg",
        "difficulty": "beginner",
        "estimated_duration": None,
        "source_platform": "YouTube",
        "published_date": None,
    },
    {
        "title": "Python for Everybody - Full University Python Course",
        "description": "Full Python for Everybody course video (Dr. Charles Severance material) on the freeCodeCamp.org YouTube channel.",
        "provider": "freeCodeCamp",
        "resource_type": "video",
        "skill": "Python",
        "topic": "Full Curriculum",
        "url": "https://www.youtube.com/watch?v=8DvywoWv6fI",
        "thumbnail_url": "https://i.ytimg.com/vi/8DvywoWv6fI/hqdefault.jpg",
        "difficulty": "beginner",
        "estimated_duration": None,
        "source_platform": "YouTube",
        "published_date": None,
    },
    {
        "title": "Python Full Course for Beginners",
        "description": "Beginner Python course video by Programming with Mosh on YouTube.",
        "provider": "Programming with Mosh",
        "resource_type": "video",
        "skill": "Python",
        "topic": "Beginner Full Course",
        "url": "https://www.youtube.com/watch?v=_uQrJ0TkZlc",
        "thumbnail_url": "https://i.ytimg.com/vi/_uQrJ0TkZlc/hqdefault.jpg",
        "difficulty": "beginner",
        "estimated_duration": None,
        "source_platform": "YouTube",
        "published_date": None,
    },
    {
        "title": "JavaScript Tutorials for Beginners",
        "description": "Beginner JavaScript tutorial playlist by Net Ninja on YouTube.",
        "provider": "Net Ninja",
        "resource_type": "video",
        "skill": "JavaScript",
        "topic": "Fundamentals",
        "url": "https://www.youtube.com/playlist?list=PL4cUxeGkcC9i9Ae2D9Ee1RvylH38dKuET",
        "thumbnail_url": "https://i.ytimg.com/vi/qoSksQ4s_hg/hqdefault.jpg",
        "difficulty": "beginner",
        "estimated_duration": None,
        "source_platform": "YouTube",
        "published_date": None,
    },
    {
        "title": "Learn JavaScript",
        "description": "Beginner Codecademy course on JavaScript fundamentals (15 hours, per the course page).",
        "provider": "Codecademy",
        "resource_type": "course",
        "skill": "JavaScript",
        "topic": "Fundamentals",
        "url": "https://www.codecademy.com/learn/introduction-to-javascript",
        "thumbnail_url": None,
        "difficulty": "beginner",
        "estimated_duration": "15 Hours",
        "source_platform": "Codecademy",
        "published_date": None,
    },
    {
        "title": "JavaScript",
        "description": "MDN Web Docs reference and guides for the JavaScript language.",
        "provider": "Mozilla",
        "resource_type": "course",
        "skill": "JavaScript",
        "topic": "Language Reference",
        "url": "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
        "thumbnail_url": None,
        "difficulty": "beginner",
        "estimated_duration": None,
        "source_platform": "MDN Web Docs",
        "published_date": None,
    },
    {
        "title": "The Modern JavaScript Tutorial",
        "description": "Open-source tutorial covering JavaScript from basics to advanced topics, maintained by Ilya Kantor.",
        "provider": "JavaScript.info",
        "resource_type": "course",
        "skill": "JavaScript",
        "topic": "Full Curriculum",
        "url": "https://javascript.info/",
        "thumbnail_url": None,
        "difficulty": "intermediate",
        "estimated_duration": None,
        "source_platform": "javascript.info",
        "published_date": None,
    },
    {
        "title": "Learn JavaScript - Full Course for Beginners",
        "description": "Full beginner JavaScript course video on the freeCodeCamp.org YouTube channel.",
        "provider": "freeCodeCamp",
        "resource_type": "video",
        "skill": "JavaScript",
        "topic": "Beginner Full Course",
        "url": "https://www.youtube.com/watch?v=PkZNo7MFNFg",
        "thumbnail_url": "https://i.ytimg.com/vi/PkZNo7MFNFg/hqdefault.jpg",
        "difficulty": "beginner",
        "estimated_duration": None,
        "source_platform": "YouTube",
        "published_date": None,
    },
    {
        "title": "JavaScript Crash Course For Beginners",
        "description": "Beginner JavaScript crash-course video by Traversy Media on YouTube.",
        "provider": "Traversy Media",
        "resource_type": "video",
        "skill": "JavaScript",
        "topic": "Crash Course",
        "url": "https://www.youtube.com/watch?v=hdI2bqOjy3c",
        "thumbnail_url": "https://i.ytimg.com/vi/hdI2bqOjy3c/hqdefault.jpg",
        "difficulty": "beginner",
        "estimated_duration": None,
        "source_platform": "YouTube",
        "published_date": None,
    },
    {
        "title": "AI For Everyone",
        "description": "Non-technical AI course by Andrew Ng on Coursera (beginner, 7 hours per the course page).",
        "provider": "DeepLearning.AI",
        "resource_type": "course",
        "skill": "AI",
        "topic": "Foundations",
        "url": "https://www.coursera.org/learn/ai-for-everyone",
        "thumbnail_url": None,
        "difficulty": "beginner",
        "estimated_duration": "7 Hours",
        "source_platform": "Coursera",
        "published_date": None,
    },
    {
        "title": "Google AI Essentials",
        "description": "Beginner Google specialization on Coursera: use generative AI tools, write effective prompts, and use AI responsibly.",
        "provider": "Google",
        "resource_type": "course",
        "skill": "AI",
        "topic": "Generative AI Productivity",
        "url": "https://www.coursera.org/learn/google-ai-essentials",
        "thumbnail_url": None,
        "difficulty": "beginner",
        "estimated_duration": "4 Hours",
        "source_platform": "Coursera",
        "published_date": None,
    },
    {
        "title": "MIT 6.S191 Introduction to Deep Learning",
        "description": "MIT open introductory program on deep learning methods with lectures, slides, and labs.",
        "provider": "MIT",
        "resource_type": "course",
        "skill": "AI",
        "topic": "Deep Learning",
        "url": "https://introtodeeplearning.com/",
        "thumbnail_url": None,
        "difficulty": "intermediate",
        "estimated_duration": None,
        "source_platform": "MIT OpenCourseWare",
        "published_date": None,
    },
    {
        "title": "Get started with AI applications and agents on Azure",
        "description": "Beginner Microsoft Learn path (7 modules): generative AI, agents, text, speech, vision, and information extraction in Microsoft Foundry.",
        "provider": "Microsoft",
        "resource_type": "course",
        "skill": "AI",
        "topic": "Azure AI",
        "url": "https://learn.microsoft.com/en-us/training/paths/get-started-with-artificial-intelligence-on-azure/",
        "thumbnail_url": None,
        "difficulty": "beginner",
        "estimated_duration": None,
        "source_platform": "Microsoft Learn",
        "published_date": None,
    },
    {
        "title": "Machine Learning & AI Courses",
        "description": "Google Cloud training hub for machine learning and AI courses, labs, paths, and certifications.",
        "provider": "Google",
        "resource_type": "course",
        "skill": "AI",
        "topic": "ML on Google Cloud",
        "url": "https://cloud.google.com/learn/training/machinelearning-ai",
        "thumbnail_url": None,
        "difficulty": "intermediate",
        "estimated_duration": None,
        "source_platform": "Google Cloud",
        "published_date": None,
    },
    {
        "title": "Machine Learning Crash Course",
        "description": "Google's fast-paced practical introduction to machine learning with videos, visualisations, and exercises.",
        "provider": "Google",
        "resource_type": "course",
        "skill": "Machine Learning",
        "topic": "Foundations",
        "url": "https://developers.google.com/machine-learning/crash-course",
        "thumbnail_url": None,
        "difficulty": "beginner",
        "estimated_duration": None,
        "source_platform": "Google Developers",
        "published_date": None,
    },
    {
        "title": "Machine Learning Specialization",
        "description": "Beginner 3-course program by DeepLearning.AI and Stanford Online, taught by Andrew Ng (2 months at 10 hours/week per the page).",
        "provider": "DeepLearning.AI",
        "resource_type": "course",
        "skill": "Machine Learning",
        "topic": "Supervised and Unsupervised Learning",
        "url": "https://www.coursera.org/specializations/machine-learning-introduction",
        "thumbnail_url": None,
        "difficulty": "beginner",
        "estimated_duration": "2 Months",
        "source_platform": "Coursera",
        "published_date": None,
    },
    {
        "title": "Machine Learning with Python",
        "description": "Hands-on IBM Skills Network course (ML0101EN): classification, regression, clustering, and dimensionality reduction (20 hours, beginner).",
        "provider": "IBM",
        "resource_type": "course",
        "skill": "Machine Learning",
        "topic": "Python ML Algorithms",
        "url": "https://cognitiveclass.ai/courses/machine-learning-with-python",
        "thumbnail_url": None,
        "difficulty": "beginner",
        "estimated_duration": "20 Hours",
        "source_platform": "Cognitive Class (IBM Skills Network)",
        "published_date": None,
    },
    {
        "title": "IBM Machine Learning Professional Certificate",
        "description": "Intermediate 6-course IBM program on Coursera: supervised/unsupervised learning, deep learning, and reinforcement learning.",
        "provider": "IBM",
        "resource_type": "course",
        "skill": "Machine Learning",
        "topic": "Professional Certificate",
        "url": "https://www.coursera.org/professional-certificates/ibm-machine-learning",
        "thumbnail_url": None,
        "difficulty": "intermediate",
        "estimated_duration": "3 Months",
        "source_platform": "Coursera",
        "published_date": None,
    },
    {
        "title": "Intro to Machine Learning",
        "description": "Kaggle Learn micro-course introducing machine learning fundamentals with hands-on exercises.",
        "provider": "Kaggle",
        "resource_type": "course",
        "skill": "Machine Learning",
        "topic": "Foundations",
        "url": "https://www.kaggle.com/learn/intro-to-machine-learning",
        "thumbnail_url": None,
        "difficulty": "beginner",
        "estimated_duration": None,
        "source_platform": "Kaggle",
        "published_date": None,
    },
    {
        "title": "Tutorial - User Guide",
        "description": "Official FastAPI tutorial user guide: build a complete API step by step.",
        "provider": "FastAPI",
        "resource_type": "course",
        "skill": "FastAPI",
        "topic": "Official Tutorial",
        "url": "https://fastapi.tiangolo.com/tutorial/",
        "thumbnail_url": None,
        "difficulty": "beginner",
        "estimated_duration": None,
        "source_platform": "FastAPI Docs",
        "published_date": None,
    },
    {
        "title": "Middleware",
        "description": "Official FastAPI docs page on creating and ordering middleware.",
        "provider": "FastAPI",
        "resource_type": "course",
        "skill": "FastAPI",
        "topic": "Middleware",
        "url": "https://fastapi.tiangolo.com/tutorial/middleware/",
        "thumbnail_url": None,
        "difficulty": "intermediate",
        "estimated_duration": None,
        "source_platform": "FastAPI Docs",
        "published_date": None,
    },
    {
        "title": "FastAPI Course for Beginners",
        "description": "Beginner FastAPI course video on the freeCodeCamp.org YouTube channel.",
        "provider": "freeCodeCamp",
        "resource_type": "video",
        "skill": "FastAPI",
        "topic": "Beginner Full Course",
        "url": "https://www.youtube.com/watch?v=tLKKmouUams",
        "thumbnail_url": "https://i.ytimg.com/vi/tLKKmouUams/hqdefault.jpg",
        "difficulty": "beginner",
        "estimated_duration": None,
        "source_platform": "YouTube",
        "published_date": None,
    },
    {
        "title": "FastAPI - A python framework | Full Course",
        "description": "Full FastAPI course video by Sarthaksavvy on YouTube.",
        "provider": "Sarthaksavvy",
        "resource_type": "video",
        "skill": "FastAPI",
        "topic": "Full Course",
        "url": "https://www.youtube.com/watch?v=7t2alSnE2-I",
        "thumbnail_url": "https://i.ytimg.com/vi/7t2alSnE2-I/hqdefault.jpg",
        "difficulty": "beginner",
        "estimated_duration": None,
        "source_platform": "YouTube",
        "published_date": None,
    },
    {
        "title": "Introduction to Cloud Computing",
        "description": "Beginner IBM Skills Network course (CC0101EN): cloud concepts, service and deployment models, and core components (12 hours).",
        "provider": "IBM",
        "resource_type": "course",
        "skill": "Cloud",
        "topic": "Cloud Concepts",
        "url": "https://cognitiveclass.ai/courses/introduction-to-cloud-computing",
        "thumbnail_url": None,
        "difficulty": "beginner",
        "estimated_duration": "12 Hours",
        "source_platform": "Cognitive Class (IBM Skills Network)",
        "published_date": None,
    },
    {
        "title": "Introduction to Cloud",
        "description": "Beginner IBM Skills Network course: cloud adoption, service models, architecture, storage, and cloud trends (6 hours).",
        "provider": "IBM",
        "resource_type": "course",
        "skill": "Cloud",
        "topic": "Cloud Basics",
        "url": "https://cognitiveclass.ai/courses/introduction-to-cloud",
        "thumbnail_url": None,
        "difficulty": "beginner",
        "estimated_duration": "6 Hours",
        "source_platform": "Cognitive Class (IBM Skills Network)",
        "published_date": None,
    },
    {
        "title": "AWS Educate - Cloud Skills for Education",
        "description": "AWS hub of free self-paced cloud training, hands-on labs, and badges for beginners.",
        "provider": "AWS",
        "resource_type": "course",
        "skill": "Cloud",
        "topic": "AWS Foundations",
        "url": "https://aws.amazon.com/education/awseducate/",
        "thumbnail_url": None,
        "difficulty": "beginner",
        "estimated_duration": None,
        "source_platform": "AWS",
        "published_date": None,
    },
    {
        "title": "AWS Cloud Practitioner Essentials",
        "description": "AWS digital training page for the Cloud Practitioner path, including the 12h 45m Essentials course.",
        "provider": "AWS",
        "resource_type": "course",
        "skill": "Cloud",
        "topic": "Cloud Practitioner",
        "url": "https://aws.amazon.com/training/digital/aws-cloud-practitioner-essentials/",
        "thumbnail_url": None,
        "difficulty": "beginner",
        "estimated_duration": "12 Hours 45 Minutes",
        "source_platform": "AWS Training",
        "published_date": None,
    },
    {
        "title": "Introduction to Cloud Infrastructure: Describe cloud concepts",
        "description": "Beginner Microsoft Learn path (3 modules): cloud concepts, benefits, and service types; first step toward AZ-900.",
        "provider": "Microsoft",
        "resource_type": "course",
        "skill": "Cloud",
        "topic": "Azure Fundamentals",
        "url": "https://learn.microsoft.com/en-us/training/paths/azure-fundamentals/",
        "thumbnail_url": None,
        "difficulty": "beginner",
        "estimated_duration": None,
        "source_platform": "Microsoft Learn",
        "published_date": None,
    },
    {
        "title": "Training resources",
        "description": "Google Cloud hub for courses, hands-on labs, learning paths, skill badges, and certification prep.",
        "provider": "Google",
        "resource_type": "course",
        "skill": "Cloud",
        "topic": "Google Cloud Training",
        "url": "https://cloud.google.com/learn/training",
        "thumbnail_url": None,
        "difficulty": "beginner",
        "estimated_duration": None,
        "source_platform": "Google Cloud",
        "published_date": None,
    },
    {
        "title": "Getting Started - Cisco Packet Tracer",
        "description": "Cisco Skills for All beginner course page for learning networking with Packet Tracer.",
        "provider": "Cisco",
        "resource_type": "course",
        "skill": "Cloud",
        "topic": "Networking Basics",
        "url": "https://skillsforall.com/course/getting-started-cisco-packet-tracer",
        "thumbnail_url": None,
        "difficulty": "beginner",
        "estimated_duration": None,
        "source_platform": "Cisco Skills for All",
        "published_date": None,
    },
    {
        "title": "Data Science 101",
        "description": "Beginner Cognitive Class course (DS0101EN): what data science is, what practitioners do, and business use cases (11 hours).",
        "provider": "IBM",
        "resource_type": "course",
        "skill": "Data Science",
        "topic": "Foundations",
        "url": "https://cognitiveclass.ai/courses/data-science-101",
        "thumbnail_url": None,
        "difficulty": "beginner",
        "estimated_duration": "11 Hours",
        "source_platform": "Cognitive Class (IBM Skills Network)",
        "published_date": None,
    },
    {
        "title": "Google Advanced Data Analytics Professional Certificate",
        "description": "Advanced 7-course Google program on Coursera: statistics, Python, regression, and machine learning.",
        "provider": "Google",
        "resource_type": "course",
        "skill": "Data Science",
        "topic": "Professional Certificate",
        "url": "https://www.coursera.org/professional-certificates/google-advanced-data-analytics",
        "thumbnail_url": None,
        "difficulty": "advanced",
        "estimated_duration": "6 Months",
        "source_platform": "Coursera",
        "published_date": None,
    },
    {
        "title": "Learn",
        "description": "Kaggle Learn hub of free interactive micro-courses on Python, pandas, visualisation, machine learning, and SQL.",
        "provider": "Kaggle",
        "resource_type": "course",
        "skill": "Data Science",
        "topic": "Micro-courses",
        "url": "https://www.kaggle.com/learn",
        "thumbnail_url": None,
        "difficulty": "beginner",
        "estimated_duration": None,
        "source_platform": "Kaggle",
        "published_date": None,
    },
    {
        "title": "IBM Data Science Professional Certificate",
        "description": "Beginner 12-course IBM program on Coursera: Python, SQL, visualisation, analysis, and machine learning.",
        "provider": "IBM",
        "resource_type": "course",
        "skill": "Data Science",
        "topic": "Professional Certificate",
        "url": "https://www.coursera.org/professional-certificates/ibm-data-science",
        "thumbnail_url": None,
        "difficulty": "beginner",
        "estimated_duration": "4 Months",
        "source_platform": "Coursera",
        "published_date": None,
    },
    {
        "title": "Data Analysis with Python",
        "description": "freeCodeCamp curriculum section covering NumPy, pandas, visualisation, and analysis.",
        "provider": "freeCodeCamp",
        "resource_type": "course",
        "skill": "Data Science",
        "topic": "Python Data Analysis",
        "url": "https://www.freecodecamp.org/learn/data-analysis-with-python/",
        "thumbnail_url": None,
        "difficulty": "beginner",
        "estimated_duration": None,
        "source_platform": "freeCodeCamp",
        "published_date": None,
    },
]
def seed_learning_resources():
    """Insert verified learning resources; refresh changed rows by URL.

    Also prunes any pre-existing rows whose URL is not in the verified
    list so the database never serves invented links or durations.
    """
    db = SessionLocal()
    try:
        existing = db.query(func.count(LearningResource.id)).scalar()
        print(f"learning_resources before seed: {existing}")
        inserted = 0
        updated = 0
        skipped = 0
        for res in RESOURCES:
            row = (
                db.query(LearningResource)
                .filter(LearningResource.url == res["url"])
                .first()
            )
            if row is None:
                db.add(LearningResource(**res))
                inserted += 1
                continue
            changed = False
            for key, value in res.items():
                if getattr(row, key) != value:
                    setattr(row, key, value)
                    changed = True
            if changed:
                updated += 1
                print(f"  UPDATE: {res['title']}")
            else:
                skipped += 1
                print(f"  SKIP (exists): {res['title']}")
        db.commit()

        # --- PRUNE stale/unverified rows (never invented data) ---
        verified_urls = {res["url"] for res in RESOURCES}
        stale = (
            db.query(LearningResource)
            .filter(LearningResource.url.notin_(verified_urls))
            .all()
        )
        for row in stale:
            print(f"  PRUNE (unverified): {row.title} | {row.url}")
            db.delete(row)
        db.commit()

        counts = (
            db.query(LearningResource.skill, func.count(LearningResource.id))
            .group_by(LearningResource.skill)
            .all()
        )
        print("learning_resources after seed (by skill):")
        for skill, count in counts:
            print(f"  {skill}: {count}")
        total = db.query(func.count(LearningResource.id)).scalar()
        print(f"Total learning_resources: {total}")
        print(f"inserted={inserted} updated={updated} skipped={skipped} pruned={len(stale)}")
    finally:
        db.close()


if __name__ == "__main__":
    seed_learning_resources()

