NEW_B = [
    ("English for Career Development", "English Speaking", "Professional English",
     "University of Pennsylvania", "https://www.coursera.org/learn/careerdevelopment",
     "beginner", "40 Hours", "english-speaking-basics", "English Speaking Basics", 2),
    ("Speak English Professionally", "Professional Communication", "Professional English",
     "Georgia Institute of Technology", "https://www.coursera.org/learn/speak-english-professionally",
     "intermediate", "16 Hours", None, None, 0),
    ("Introduction to Public Speaking", "Public Speaking", "Foundations",
     "University of Washington", "https://www.coursera.org/learn/public-speaking",
     "beginner", "16 Hours", "public-speaking-essentials", "Public Speaking Essentials", 1),
    ("Dynamic Public Speaking", "Public Speaking", "Delivery",
     "University of Washington", "https://www.coursera.org/specializations/public-speaking",
     "intermediate", "4 Months", "public-speaking-essentials", "Public Speaking Essentials", 2),
    ("Business English Communication Skills", "Business Writing", "Business English",
     "University of Washington", "https://www.coursera.org/specializations/business-english",
     "intermediate", "5 Months", None, None, 0),
    ("Successful Interviewing", "Interview Communication", "Interviews",
     "University of Maryland", "https://www.coursera.org/learn/successful-interviewing",
     "beginner", "10 Hours", "interview-preparation", "Interview Preparation", 1),
    ("How to Write a Resume (Project-Centered Course)", "Resume Building", "Resume",
     "State University of New York", "https://www.coursera.org/learn/how-to-write-a-resume",
     "beginner", "4 Hours", "resume-building", "Resume Building", 1),
    ("Interviewing and Resume Writing in English", "Interview Preparation", "Interviews",
     "University of Maryland", "https://www.coursera.org/specializations/english-interview-resume",
     "beginner", "3 Months", "interview-preparation", "Interview Preparation", 2),
    ("Teamwork Skills: Communicating Effectively in Groups", "Team Collaboration", "Teamwork",
     "University of Colorado", "https://www.coursera.org/learn/teamwork-skills",
     "beginner", "11 Hours", None, None, 0),
    ("Introduction to Logic and Critical Thinking", "Problem Solving", "Critical Thinking",
     "Duke University", "https://www.coursera.org/learn/logic-critical-thinking",
     "beginner", "11 Hours", None, None, 0),
    ("Aptitude Preparation — Quantitative Aptitude", "Aptitude", "Quantitative Aptitude",
     "IndiaBIX", "https://www.indiabix.com/aptitude/questions-and-answers/",
     "beginner", None, None, None, 0),
    ("Build Your Professional Profile with LinkedIn", "LinkedIn Profile Building", "LinkedIn",
     "Coursera Project Network", "https://www.coursera.org/projects/linkedin-profile",
     "beginner", "2 Hours", None, None, 0),
    ("Excel Skills for Business: Essentials", "Excel", "Essentials",
     "Macquarie University", "https://www.coursera.org/learn/excel-essentials",
     "beginner", "26 Hours", "excel-fundamentals", "Excel Fundamentals", 1),
    ("Data Analysis with Python", "Data Analysis", "Python Data Analysis",
     "freeCodeCamp", "https://www.freecodecamp.org/learn/data-analysis-with-python/",
     "beginner", None, None, None, 0),
    ("Introduction to Project Management", "Project Management", "Foundations",
     "University of Adelaide", "https://www.edx.org/learn/project-management/the-university-of-adelaide-introduction-to-project-management",
     "beginner", "8 Weeks", None, None, 0),
    ("Design Thinking for Innovation", "Design Thinking", "Innovation",
     "University of Virginia", "https://www.coursera.org/learn/uva-darden-design-thinking-innovation",
     "beginner", "8 Hours", None, None, 0),
    ("Entrepreneurship: Launching an Innovative Business", "Entrepreneurship", "Foundations",
     "University of Maryland", "https://www.coursera.org/learn/launching-innovative-business",
     "beginner", "13 Hours", None, None, 0),
]
